import React from 'react'
import { hydrate } from 'react-dom'
import { createStore } from 'redux';
import { Provider } from 'react-redux';
import { BrowserRouter, Route } from 'react-router-dom';
import routes from '../both/routes';
import reducers from '../both/reducers';
import { ReduxAsyncConnect } from 'redux-connect';
import App from '../both/app.js';

// This value is rendered into the DOM by the server
const initialState = window.__INITIAL_STATE;

// Create store with the initial state generated by the server
const store = createStore(reducers, initialState);

hydrate(
  <Provider store={store}>
    <BrowserRouter>
      <ReduxAsyncConnect routes={routes} />
    </BrowserRouter>
  </Provider>,
  document.getElementById('app')
);
