import React from 'react';
import { createStore } from 'redux';
import { Provider } from 'react-redux';
import { renderToString } from 'react-dom/server';
import { StaticRouter } from 'react-router';
import { ReduxAsyncConnect, loadOnServer } from 'redux-connect';
import { parse as parseUrl } from 'url';
import Helmet from 'react-helmet';
import { ChunkExtractor } from '@loadable/server';
import path from 'path';
import fs from 'fs';

import { createRootReducer }  from '../../../both/website-main/reducers';
import { setAppInitialState } from '../../../both/website-main/app-reducer';
import routes                 from '../../../both/website-main/routes';

import renderLayout from '../../views/layout';
import populateData from '../../data';

// stats file generated by webpack, this is used for SSR of code-split pages
const statsFile = path.resolve(
  __dirname,
  '../../../public/loadable-stats.json',
)

const { NODE_ENV } = process.env;

const publicPath = (
  NODE_ENV === 'staged'     ? `${ CDN_URL }assets/staged/`
: NODE_ENV === 'production' ? `${ CDN_URL }assets/`
: '/'
);

export const mainController = (request, response) => {
  const url = request.originalUrl || request.url;
  const location = parseUrl(url);

  // load data out of keystone's interface to mongo
  let [pagePath, ...args] = request.path.split('/').splice(1);
  populateData(pagePath, args, request, response).then(data => {
    // get the site config out of locals, and initialize
    // the appReducer's initial state
    setAppInitialState(response.locals);

    // initialize a store for rendering app
    const store = createStore(createRootReducer())

    // wait for all components to finish async requests
    loadOnServer({ location, routes, store, data })
    .then(() => {
      const context = {};
      const extractor = new ChunkExtractor({
        statsFile,
        publicPath,
      });

      // load in compnents that are code split
      const jsx = extractor.collectChunks(
        <Provider store={store}>
          <StaticRouter
            location={location}
            context={context}
          >
            <ReduxAsyncConnect routes={routes} />
          </StaticRouter>
        </Provider>
      );

      // handle redirects
      if(context.url) {
        request.header('Location', context.url)
        return response.send(302)
      }

      // generate a string that we will render to the page
      const html = renderToString(jsx);

      // get values for head: title, meta tags
      const head = Helmet.renderStatic();

      // render the page, and send it to the client
      response.send(renderLayout(head, html, 'main', store.getState(), extractor, !!(request.user && request.user.isAdmin)))

    })
    .catch(err => {
      console.error(err);
      response.status(500).end();
    });
  })
  .catch(err => {
    console.error(err);
    response.status(500).end();
  });
};
